
/* -------------------------------------------------------------------------
 * !!! AUTOMATICALLY GENERATED CODE !!!
 * -------------------------------------------------------------------------
 * This file was automatically generated by the OrangeBits compiler.  
 * Compiled on:  2/9/2012 5:58:40 PM
 * Compiled by: REDMOND\justbe
 * Source: C:\Users\justbe\Dropbox\Code\OrangeBits\Demo\BadSyntax.coffee      
 * -------------------------------------------------------------------------*/


